# Server groups
# Config Variables

one:
 hostname: 172.16.45.132
 server_port : 3000
 raft_port : 3001
 #connection_port : [4001, 5001]
 primary : 1


two:
 hostname: 172.16.45.133
 server_port : 3000
 primary : 0
 raft_port: 3001


three:
 hostname: 172.16.45.134
 server_port : 3000
 primary : 0
 raft_port: 3001

LRUCapacity: 5

UPLOAD_SHARD_SIZE: 52428800

super_node_address: "172.16.45.131:50051"
