# Server groups
# Config Variables

one:
 hostname: 10.160.0.13
 server_port : 3000
 raft_port : 3001
 #connection_port : [4001, 5001]
 primary : 1


two:
 hostname: 10.148.0.2
 server_port : 3000
 primary : 0
 raft_port: 3001


three:
 hostname: 10.146.0.2
 server_port : 3000
 primary : 0
 raft_port: 3001

LRUCapacity: 5

UPLOAD_SHARD_SIZE: 52428800

super_node_address: "10.160.0.12:50051"
